### ISSUE TITLE
Alucart GitHub tutorial

### ISSUE THREAD

**Issue by Kimel-PK** [Gamedev-Students-Association/Sekcja_Unity_2024#4]
Wrzuć do `Assets/Tutorial` dowolny plik, commituj i utwórz ze swojej gałęzi pull requesta

**Comment by DawidBukowski** [comment]
Czy wrzuciłem te zmiany poprawnie ? bo chyba nie tak to miało wyglądać :(

**Comment by Kimel-PK** [comment]
Prawie dobrze, tylko to nie musi być draft pull request tylko zwykły pull request, 

W ogóle to trochę zdziwiony jestem bo z tego co kojarzę to tylko organizacja z płatnym githubem może robić draft PR 😆 

![obraz](https://github.com/user-attachments/assets/568d5fd0-80d8-46c2-843f-f1f30ee5f1b0)

Nie jestem pewien ale chyba kliknięcie w to powinno go zmienić w zwykłego pull requesta

**Comment by Kimel-PK** [comment]
Mhm jeszcze teraz widzę, że zamiast commitować bezpośrednio do repo to zrobiłeś forka? Czyli zamiast pobrać sobie repo do którego masz dostęp to zrobiłeś klona na swoje konto prywatne
